services:
  api:
    container_name: ${RAILS_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ${RAILS_DOCKERFILE}
    env_file:
      - .env
    volumes:
      - .:/rails
    ports:
      - ${RAILS_PORT_MAP}
    depends_on:
      db:
        condition: service_healthy
    # Run server only
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  waka:
    container_name: ${WAKA_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ${RAILS_DOCKERFILE}
    env_file:
      - .env
    volumes:
      - .:/rails
    depends_on:
      db:
        condition: service_healthy
    command: ["./bin/jobs"]

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:18-alpine
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    # ports: # enable to access from outside of docker
    #   - ${PG_PORT_MAP}

  # Media Worker [OPTIONAL] - processes :media queue only
  media:
    container_name: ${MEDIA_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ${RAILS_DOCKERFILE}
    env_file:
      - .env
    volumes:
      - .:/rails
    depends_on:
      db:
        condition: service_healthy
    command: ["./bin/jobs", "-c", "config/queue.media.yml"]

volumes:
  postgres:
