# config/queue.yml
# TODO: need to test with dev
default: &default
  dispatchers: # move scheduled queue to ready queue when time's up [not immediate jobs]
    - polling_interval: 1 # check scheduled queue every 1s & move to ready when scheduled time's up
      batch_size: 500 # 2000 notis => 4 x 500 notis move to ready queue
      concurrency_maintenance_interval: 60 # check blocked jobs every min. not affect normal ready-job polling. default is 600s.

development:
  <<: *default
  workers: # idle worker checks ready queue & execute (excludes :media which is handled by media container)
    - queues: "default,payments,notifications,storage,ai"
      threads: 3
      polling_interval: 0.5 # 2 checks per second

test:
  <<: *default
  workers:
    - queues: "*"
      threads: 1
      polling_interval: 0.5

production:
  <<: *default

  workers:
    # Payment operations and ordinary application jobs
    - queues: "payments,default"
      threads: 3
      polling_interval: 0.2

    # Everything coordinated by NotificationService
    - queues: "notifications"
      threads: 3
      polling_interval: 0.5

    # Storage uploads, deletion
    - queues: "storage"
      threads: 2
      polling_interval: 1

    # AI
    - queues: "ai"
      threads: 2
      polling_interval: 0.5

    # NOTE: :media queue is NOT listed here.
    # It is processed exclusively by the `media` container
    # using config/queue.media.yml.
