module MessageService
  class Auth < Base
    SIGNED_IN = "auth.signed_in"
    SIGN_IN_FAILED = "auth.sign_in_failed"
    SIGNED_OUT = "auth.signed_out"
    SIGN_OUT_FAILED = "auth.sign_out_failed"
    SIGNED_UP = "auth.signed_up"
    SIGN_UP_FAILED = "auth.sign_up_failed"
    GOOGLE_AUTH_FAILED = "auth.google_auth_failed"
    GOOGLE_ACCOUNT_EXISTS = "auth.google_account_exists"
    CONFIRMATION_EMAIL_QUEUED = "auth.confirmation_email_queued"
    EMAIL_ALREADY_CONFIRMED = "auth.email_already_confirmed"
    EMAIL_CONFIRMATION_FAILED = "auth.email_confirmation_failed"
    EMAIL_CONFIRMED = "auth.email_confirmed"
    USER_NOT_FOUND = "auth.user_not_found"
    EMAIL_NOT_FOUND = "auth.email_not_found"
    ACTIVE_SESSION_NOT_FOUND = "auth.active_session_not_found"
    PASSWORD_RESET_QUEUED = "auth.password_reset_queued"
    PASSWORD_RESET = "auth.password_reset"
    PASSWORD_RESET_FAILED = "auth.password_reset_failed"
    INVALID_CREDENTIALS = "auth.invalid_credentials"
    INVALID_TOKEN = "auth.invalid_token"
    ACCOUNT_CREATED_AND_SIGNED_IN = "auth.account_created_and_signed_in"
    ACCOUNT_DELETED = "auth.account_deleted"
    EMAIL_REQUIRED = "auth.email_required"
    EMAIL_MISSING = "auth.email_missing"
    USER_EXISTENCE_CHECKED = "auth.user_existence_checked"
    TOO_MANY_ATTEMPTS = "auth.too_many_attempts"
    TOO_MANY_ATTEMPTS_WITH_WAIT = "auth.too_many_attempts_with_wait"
    SET_PASSCODE = "auth.set_passcode"
    CHALLENGE_AND_PASSCODE_REQUIRED = "auth.challenge_and_passcode_required"
  end
end
