module MessageService
  class Notification < Base
    QUEUED = "notification.queued"
    FETCHED = "notification.fetched"
    READ = "notification.read"
    READ_ALL = "notification.read_all"
    RECIPIENTS_FETCHED = "notification.recipients_fetched"
    TEMPLATES_FETCHED = "notification.templates_fetched"
    NOT_FOUND = "notification.not_found"
    QUEUE_FAILED = "notification.queue_failed"
    INVALID_REQUEST = "notification.invalid_request"
    TITLE_REQUIRED = "notification.title_required"
    MESSAGE_REQUIRED = "notification.message_required"
    CHANNEL_REQUIRED = "notification.channel_required"
    INVALID_CHANNEL = "notification.invalid_channel"
    INVALID_AUDIENCE = "notification.invalid_audience"
    USER_IDS_REQUIRED = "notification.user_ids_required"
    ROLE_IDS_REQUIRED = "notification.role_ids_required"
    INVALID_DATA = "notification.invalid_data"
    NO_RECIPIENTS = "notification.no_recipients"
    EVENT_REQUIRED = "notification.event_required"
    INVALID_EVENT = "notification.invalid_event"
    DEFAULT_TITLE = "notification.default_title"
    DEFAULT_BODY = "notification.default_body"
    TEMPLATE_NOT_FOUND = "notification.template_not_found"
    WELCOME_TITLE = "notification.welcome.title"
    WELCOME_BODY = "notification.welcome.body"
    SIGN_IN_ALERT_TITLE = "notification.sign_in_alert.title"
    SIGN_IN_ALERT_BODY = "notification.sign_in_alert.body"
  end
end
