module MessageService
  class Notification < Base
    QUEUED = "notification.queued"
    RECIPIENTS_FETCHED = "notification.recipients_fetched"
    TEMPLATES_FETCHED = "notification.templates_fetched"
    QUEUE_FAILED = "notification.queue_failed"
    INVALID_REQUEST = "notification.invalid_request"
    TITLE_REQUIRED = "notification.title_required"
    MESSAGE_REQUIRED = "notification.message_required"
    CHANNEL_REQUIRED = "notification.channel_required"
    INVALID_CHANNEL = "notification.invalid_channel"
    INVALID_AUDIENCE = "notification.invalid_audience"
    USER_IDS_REQUIRED = "notification.user_ids_required"
    ROLE_IDS_REQUIRED = "notification.role_ids_required"
    INVALID_DATA = "notification.invalid_data"
    NO_RECIPIENTS = "notification.no_recipients"
    EVENT_REQUIRED = "notification.event_required"
    INVALID_EVENT = "notification.invalid_event"
    DEFAULT_TITLE = "notification.default_title"
    DEFAULT_BODY = "notification.default_body"
    TEMPLATE_NOT_FOUND = "notification.template_not_found"
    WELCOME_TITLE = "notification.welcome.title"
    WELCOME_BODY = "notification.welcome.body"
    SIGN_IN_ALERT_TITLE = "notification.sign_in_alert.title"
    SIGN_IN_ALERT_BODY = "notification.sign_in_alert.body"
    NOTIFICATIONS_FETCHED = "notification.notifications_fetched"
    UNREAD_COUNT_FETCHED = "notification.unread_count_fetched"
    MARKED_AS_READ = "notification.marked_as_read"
    ALL_MARKED_AS_READ = "notification.all_marked_as_read"
    NOTIFICATION_DELETED = "notification.notification_deleted"
    NOTIFICATION_NOT_FOUND = "notification.notification_not_found"
    TEMPLATE_CREATED = "notification.template_created"
    TEMPLATE_UPDATED = "notification.template_updated"
    TEMPLATE_DISCARDED = "notification.template_discarded"
    TEMPLATE_UNDISCARDED = "notification.template_undiscarded"
    NOTIFICATION_CREATED = "notification.notification_created"
    NOTIFICATION_UPDATED = "notification.notification_updated"
    NOTIFICATION_DISCARDED = "notification.notification_discarded"
    NOTIFICATION_UNDISCARDED = "notification.notification_undiscarded"
  end
end
