module MessageService
  class Payment < Base
    # API responses
    PRODUCTS_FETCHED = "payment.products.fetched"
    PRODUCT_FETCHED = "payment.products.fetched_one"
    PRODUCT_CREATED = "payment.products.created"
    PRODUCT_CREATE_FAILED = "payment.products.create_failed"
    PRODUCT_UPDATED = "payment.products.updated"
    PRODUCT_UPDATE_FAILED = "payment.products.update_failed"
    PRODUCT_DISCARDED = "payment.products.discarded"
    PRODUCT_DISCARD_FAILED = "payment.products.discard_failed"
    DISCARDED_PRODUCTS_FETCHED = "payment.products.discarded_fetched"
    PRODUCT_RESTORED = "payment.products.restored"
    PRODUCT_RESTORE_FAILED = "payment.products.restore_failed"
    TRANSACTIONS_FETCHED = "payment.transactions.fetched"
    TRANSACTION_FETCHED = "payment.transactions.fetched_one"
    RECENT_TRANSACTIONS_FETCHED = "payment.transactions.recent_fetched"
    SUBSCRIPTIONS_FETCHED = "payment.subscriptions.fetched"
    SUBSCRIPTION_FETCHED = "payment.subscriptions.fetched_one"

    # Coupons
    COUPONS_FETCHED = "payment.coupons.fetched"
    COUPON_FETCHED = "payment.coupons.fetched_one"
    COUPON_CREATED = "payment.coupons.created"
    COUPON_CREATE_FAILED = "payment.coupons.create_failed"
    BATCH_COUPONS_CREATED = "payment.coupons.batch_created"
    BATCH_COUPONS_CREATE_FAILED = "payment.coupons.batch_create_failed"
    COUPON_UPDATED = "payment.coupons.updated"
    COUPON_UPDATE_FAILED = "payment.coupons.update_failed"
    COUPON_DISCARDED = "payment.coupons.discarded"
    COUPON_DISCARD_FAILED = "payment.coupons.discard_failed"
    DISCARDED_COUPONS_FETCHED = "payment.coupons.discarded_fetched"
    COUPON_RESTORED = "payment.coupons.restored"
    COUPON_RESTORE_FAILED = "payment.coupons.restore_failed"
    COUPON_DELETED = "payment.coupons.deleted"
    COUPON_DESTROY_FAILED = "payment.coupons.destroy_failed"
    NO_COUPONS_SELECTED = "payment.coupons.no_coupons_selected"
    BATCH_DISCARDED = "payment.coupons.batch_discarded"
    BATCH_RESTORED = "payment.coupons.batch_restored"
    BATCH_DELETED = "payment.coupons.batch_deleted"
    RECYCLE_BIN_EMPTIED = "payment.coupons.recycle_bin_emptied"
    COUPON_VALID = "payment.coupons.valid"
    COUPON_INVALID = "payment.coupons.invalid"
    COUPON_NOT_FOUND = "payment.coupons.not_found"
    COUPON_EXPIRED = "payment.coupons.expired"
    COUPON_USAGE_LIMIT_REACHED = "payment.coupons.usage_limit_reached"
    COUPON_USER_LIMIT_REACHED = "payment.coupons.user_limit_reached"
    COUPON_NOT_APPLICABLE_PRODUCT = "payment.coupons.not_applicable_product"
    COUPON_NOT_APPLICABLE_ROLE = "payment.coupons.not_applicable_role"
    COUPON_NOT_APPLICABLE_USER = "payment.coupons.not_applicable_user"
    COUPON_CURRENCY_MISMATCH = "payment.coupons.currency_mismatch"
    TOO_MANY_COUPON_ATTEMPTS = "payment.coupons.too_many_attempts"
    TOO_MANY_COUPON_ATTEMPTS_WITH_WAIT = "payment.coupons.too_many_attempts_with_wait"
    USER_COUPONS_FETCHED = "payment.user_coupons.fetched"
    USER_COUPON_FETCHED = "payment.user_coupons.fetched_one"

    ALREADY_SUBSCRIBED = "payment.checkout.already_subscribed"
    ACTIVE_SUBSCRIPTION_EXISTS = "payment.checkout.active_subscription_exists"
    ACTIVE_ACCESS_EXISTS = "payment.checkout.active_access_exists"
    FREE_ACCESS_GRANTED = "payment.checkout.free_access_granted"
    CHECKOUT_CREATE_FAILED = "payment.checkout.create_failed"
    CHECKOUT_CREATED = "payment.checkout.created"
    SESSION_NOT_FOUND = "payment.checkout.session_not_found"
    SESSION_STATUS = "payment.checkout.session_status"
    CANNOT_CANCEL = "payment.subscriptions.cannot_cancel"
    ALREADY_SCHEDULED_FOR_CANCELLATION =
      "payment.subscriptions.already_scheduled_for_cancellation"
    NOT_CANCELABLE = "payment.subscriptions.not_cancelable"
    CANCEL_FAILED = "payment.subscriptions.cancel_failed"
    CANNOT_RESUME = "payment.subscriptions.cannot_resume"
    NOT_SCHEDULED_FOR_CANCELLATION =
      "payment.subscriptions.not_scheduled_for_cancellation"
    RESUME_FAILED = "payment.subscriptions.resume_failed"
    CANNOT_REMOVE = "payment.subscriptions.cannot_remove"
    ONLY_ENDED_CAN_BE_REMOVED = "payment.subscriptions.only_ended_can_be_removed"
    REMOVED = "payment.subscriptions.removed"

    # Webhook responses
    INVALID_STRIPE_SIGNATURE = "payment.webhooks.invalid_stripe_signature"
    INVALID_JSON_PAYLOAD = "payment.webhooks.invalid_json_payload"
    WEBHOOK_QUEUE_FAILED = "payment.webhooks.queue_failed"
    WEBHOOK_PERSIST_FAILED = "payment.webhooks.persist_failed"
    WEBHOOK_PROCESSING_FAILED = "payment.webhooks.processing_failed"

    # Notifications
    PAYMENT_SUCCESS_TITLE = "payment.notifications.payment_success.title"
    PAYMENT_SUCCESS_BODY = "payment.notifications.payment_success.body"
    SUBSCRIPTION_CREATED_TITLE = "payment.notifications.subscription_created.title"
    SUBSCRIPTION_CREATED_BODY = "payment.notifications.subscription_created.body"
    SUBSCRIPTION_CANCELED_TITLE = "payment.notifications.subscription_canceled.title"
    SUBSCRIPTION_CANCELED_BODY = "payment.notifications.subscription_canceled.body"
    SUBSCRIPTION_CANCELED_BODY_WITH_DATE =
      "payment.notifications.subscription_canceled.body_with_date"
    SUBSCRIPTION_RESUMED_TITLE = "payment.notifications.subscription_resumed.title"
    SUBSCRIPTION_RESUMED_BODY = "payment.notifications.subscription_resumed.body"
    PAYMENT_FAILED_TITLE = "payment.notifications.payment_failed.title"
    PAYMENT_FAILED_BODY = "payment.notifications.payment_failed.body"
    TODAY = "payment.notifications.today"
    END_OF_PERIOD = "payment.notifications.end_of_period"
  end
end
